//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000(void);
int64_t function_1003(void);
int64_t function_10c0(int64_t a1);
void function_10c3(int64_t * d);
int64_t function_10d0(int64_t a1);
void function_10d3(int64_t * ptr);
int64_t function_10e0(int64_t a1);
int32_t function_10e3(int32_t c);
int64_t function_10f0(char * a1, int32_t a2, int64_t a3);
int32_t function_10f3(char * s);
int64_t function_1100(int64_t a1);
int32_t function_1103(char * s);
int64_t function_1110(int64_t a1);
void function_1113(void);
int64_t function_1120(char * a1);
int32_t function_1123(char * format, ...);
int64_t function_1130(int64_t a1, int64_t a2);
int32_t function_1133(char * s, struct _IO_FILE * stream);
int64_t function_1140(char * a1, int64_t * a2, int64_t a3, int32_t a4);
int32_t function_1143(char * format, ...);
int64_t function_1150(int64_t a1);
char * function_1153(char * s);
int64_t function_1163(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_11c0(void);
int64_t function_1203(void);
int64_t function_1240(void);
int64_t function_1243(void);
int64_t function_1249(int64_t a1, int64_t * a2, int64_t a3, int32_t a4);
int64_t function_124c(int64_t a1, int64_t a2);
int64_t function_130a(int64_t a1, int64_t a2);
int64_t function_15b3(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1623(void);
int64_t function_162b(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1240; // 0x3d78
int64_t g2 = 0x1200; // 0x3d80
int64_t g3 = 0; // 0x4010
char g4 = 0; // 0x4018
int32_t g5;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t function_1000(void) {
    // 0x1000
    int64_t result; // 0x1000
    return result;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g5;
    }
    // 0x1016
    return result;
}

// Address range: 0x10c0 - 0x10c1
int64_t function_10c0(int64_t a1) {
    // 0x10c0
    int64_t result; // 0x10c0
    return result;
}

// Address range: 0x10c3 - 0x10cb
void function_10c3(int64_t * d) {
    // 0x10c3
    __cxa_finalize(d);
}

// Address range: 0x10d0 - 0x10d1
int64_t function_10d0(int64_t a1) {
    // 0x10d0
    int64_t result; // 0x10d0
    return result;
}

// Address range: 0x10d3 - 0x10db
void function_10d3(int64_t * ptr) {
    // 0x10d3
    free(ptr);
}

// Address range: 0x10e0 - 0x10e1
int64_t function_10e0(int64_t a1) {
    // 0x10e0
    int64_t result; // 0x10e0
    return result;
}

// Address range: 0x10e3 - 0x10eb
int32_t function_10e3(int32_t c) {
    // 0x10e3
    return putchar(c);
}

// Address range: 0x10f0 - 0x10f1
int64_t function_10f0(char * a1, int32_t a2, int64_t a3) {
    // 0x10f0
    int64_t result; // 0x10f0
    return result;
}

// Address range: 0x10f3 - 0x10fb
int32_t function_10f3(char * s) {
    // 0x10f3
    return puts(s);
}

// Address range: 0x1100 - 0x1101
int64_t function_1100(int64_t a1) {
    // 0x1100
    int64_t result; // 0x1100
    return result;
}

// Address range: 0x1103 - 0x110b
int32_t function_1103(char * s) {
    // 0x1103
    return strlen(s);
}

// Address range: 0x1110 - 0x1111
int64_t function_1110(int64_t a1) {
    // 0x1110
    int64_t result; // 0x1110
    return result;
}

// Address range: 0x1113 - 0x111b
void function_1113(void) {
    // 0x1113
    __stack_chk_fail();
}

// Address range: 0x1120 - 0x1121
int64_t function_1120(char * a1) {
    // 0x1120
    int64_t result; // 0x1120
    return result;
}

// Address range: 0x1123 - 0x112b
int32_t function_1123(char * format, ...) {
    // 0x1123
    return printf(format);
}

// Address range: 0x1130 - 0x1131
int64_t function_1130(int64_t a1, int64_t a2) {
    // 0x1130
    int64_t result; // 0x1130
    return result;
}

// Address range: 0x1133 - 0x113b
int32_t function_1133(char * s, struct _IO_FILE * stream) {
    // 0x1133
    return fputs(s, stream);
}

// Address range: 0x1140 - 0x1141
int64_t function_1140(char * a1, int64_t * a2, int64_t a3, int32_t a4) {
    // 0x1140
    int64_t result; // 0x1140
    return result;
}

// Address range: 0x1143 - 0x114b
int32_t function_1143(char * format, ...) {
    // 0x1143
    return scanf(format);
}

// Address range: 0x1150 - 0x1151
int64_t function_1150(int64_t a1) {
    // 0x1150
    int64_t result; // 0x1150
    return result;
}

// Address range: 0x1153 - 0x115b
char * function_1153(char * s) {
    // 0x1153
    return strdup(s);
}

// Address range: 0x1160 - 0x1161
int64_t entry_point(void) {
    // 0x1160
    int64_t result; // 0x1160
    return result;
}

// Address range: 0x1163 - 0x11b9
int64_t function_1163(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x1163
    int64_t v1; // 0x1163
    __libc_start_main(0x1307, (int32_t)a4, (char **)&v1, (void (*)())0x15b0, (void (*)())0x1620, (void (*)())a3);
    __asm_hlt();
    return &g3;
}

// Address range: 0x11c0 - 0x11f9
int64_t function_11c0(void) {
    // 0x11c0
    return 0;
}

// Address range: 0x1203 - 0x1239
int64_t function_1203(void) {
    // 0x1203
    if (g4 != 0) {
        // 0x1238
        int64_t result; // 0x1203
        return result;
    }
    // 0x120d
    int64_t result2; // 0x1203
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x121b
        result2 = function_10c0(*(int64_t *)0x4008);
    }
    // 0x1227
    g4 = 1;
    return result2;
}

// Address range: 0x1240 - 0x1241
int64_t function_1240(void) {
    // 0x1240
    int64_t result; // 0x1240
    return result;
}

// Address range: 0x1243 - 0x1249
int64_t function_1243(void) {
    // 0x1243
    return function_11c0();
}

// Address range: 0x1249 - 0x124a
int64_t function_1249(int64_t a1, int64_t * a2, int64_t a3, int32_t a4) {
    // 0x1249
    int64_t result; // 0x1249
    return result;
}

// Address range: 0x124c - 0x1307
int64_t function_124c(int64_t a1, int64_t a2) {
    int64_t result = function_1150(a2); // 0x1264
    int64_t v1 = function_1100(result); // 0x1274
    if (v1 == 0) {
        // 0x1301
        return result;
    }
    int64_t v2 = 0; // 0x12ff
    char * v3 = (char *)(v2 + result); // 0x1292
    char v4 = *v3; // 0x1292
    int32_t v5; // 0x12bc
    char v6; // 0x124c
    if (v4 >= 33 && v4 != 127) {
        // 0x12ab
        v5 = (int32_t)v4 + 47;
        v6 = v5;
        if (v5 < 127) {
            // 0x12df
            *v3 = v6;
        } else {
            // 0x12c8
            *v3 = v6 - 94;
        }
    }
    // 0x12f2
    v2++;
    while (v2 != v1) {
        // 0x1287
        v3 = (char *)(v2 + result);
        v4 = *v3;
        if (v4 >= 33 && v4 != 127) {
            // 0x12ab
            v5 = (int32_t)v4 + 47;
            v6 = v5;
            if (v5 < 127) {
                // 0x12df
                *v3 = v6;
            } else {
                // 0x12c8
                *v3 = v6 - 94;
            }
        }
        // 0x12f2
        v2++;
    }
    // 0x1301
    return result;
}

// Address range: 0x130a - 0x15aa
int64_t function_130a(int64_t a1, int64_t a2) {
    int64_t v1 = __readfsqword(40); // 0x131a
    int64_t v2 = 0x4c75257240343a41; // bp-56, 0x133d
    function_1120("What's my favorite number? ");
    int32_t v3; // bp-72, 0x130a
    function_1140("%d", (int64_t *)&v3, 0xd2c49, 0xd2c49);
    if (v3 != 0x86187) {
        // 0x1583
        function_10f0("Sorry, that's not it!", 0xd2c49, 0xd2c49);
    } else {
        int64_t v4 = function_1249(0, &v2, 0xd2c49, 0xd2c49); // 0x154c
        function_1130(v4, g3);
        function_10e0(10);
        function_10d0(v4);
    }
    int64_t v5 = __readfsqword(40) ^ v1; // 0x1598
    int64_t result = 0; // 0x15a1
    if (v5 != 0) {
        // 0x15a3
        result = function_1110(v5);
    }
    // 0x15a8
    return result;
}

// Address range: 0x15b3 - 0x1615
int64_t function_15b3(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_1000(); // 0x15dc
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1606
        return result;
    }
    int64_t v1 = 0; // 0x15e5
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x15f0
        v1++;
    }
    // 0x1606
    return result;
}

// Address range: 0x1623 - 0x1625
int64_t function_1623(void) {
    // 0x1623
    int64_t result; // 0x1623
    return result;
}

// Address range: 0x162b - 0x1635
int64_t function_162b(void) {
    // 0x162b
    int64_t result; // 0x162b
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// int fputs(const char * restrict s, FILE * restrict stream);
// void free(void * ptr);
// int printf(const char * restrict format, ...);
// int putchar(int c);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// char * strdup(const char * s);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 34
