/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// int fclose(FILE *stream);
// size_t strlen(const char *s);
// FILE *fopen(const char *filename, const char *modes);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int _gmon_start__(void); weak
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
__int64 realrand();
__int64 pseudorand();
int __cdecl main(int argc, const char **argv, const char **envp);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
char _bss_start; // weak
int seed; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (0000000000400508) ----------------------------------------------------
int init_proc()
{
  void *v0; // rax@1

  v0 = &__gmon_start__;
  if ( &__gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 4005B0: using guessed type int _gmon_start__(void);

//----- (00000000004005C0) ----------------------------------------------------
#error "4005C6: positive sp value has been found (funcsize=3)"

//----- (00000000004005F0) ----------------------------------------------------
int deregister_tm_clones()
{
  signed __int64 v0; // rax@1

  v0 = 6295655LL - (_QWORD)&_bss_start;
  if ( (unsigned __int64)(6295655LL - (_QWORD)&_bss_start) > 0xE )
    LODWORD(v0) = 0;
  return v0;
}
// 601060: using guessed type char _bss_start;

//----- (0000000000400630) ----------------------------------------------------
int register_tm_clones()
{
  return 0;
}

//----- (0000000000400670) ----------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax@2

  if ( !_bss_start )
  {
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 601060: using guessed type char _bss_start;

//----- (0000000000400690) ----------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 400690: could not find valid save-restore pair for rbp

//----- (00000000004006B6) ----------------------------------------------------
__int64 realrand()
{
  __int64 result; // rax@1
  __int64 v1; // rsi@1
  int ptr; // [sp+Ch] [bp-14h]@1
  FILE *stream; // [sp+10h] [bp-10h]@1
  __int64 v4; // [sp+18h] [bp-8h]@1

  v4 = *MK_FP(__FS__, 40LL);
  stream = fopen("/dev/urandom", "r");
  fread(&ptr, 4uLL, 1uLL, stream);
  fclose(stream);
  result = (unsigned int)(ptr % 80);
  v1 = *MK_FP(__FS__, 40LL) ^ v4;
  return result;
}

//----- (0000000000400745) ----------------------------------------------------
__int64 pseudorand()
{
  seed = (unsigned __int8)(-71 * seed - 111);
  return (unsigned int)seed;
}
// 601064: using guessed type int seed;

//----- (000000000040076B) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char v3; // bl@2
  int result; // eax@4
  __int64 v5; // rcx@4
  char v6; // [sp+Bh] [bp-85h]@2
  int v7; // [sp+Ch] [bp-84h]@1
  int v8; // [sp+10h] [bp-80h]@1
  int v9; // [sp+14h] [bp-7Ch]@2
  FILE *stream; // [sp+18h] [bp-78h]@1
  char ptr[88]; // [sp+20h] [bp-70h]@1
  __int64 v12; // [sp+78h] [bp-18h]@1

  v12 = *MK_FP(__FS__, 40LL);
  stream = fopen("flag.in", "r");
  fread(ptr, 1uLL, 0x50uLL, stream);
  fclose(stream);
  stream = fopen("flag.out", "wb");
  seed = realrand();
  v7 = 0;
  v8 = strlen(ptr);
  while ( v7 < v8 )
  {
    v3 = ptr[v7];
    v9 = pseudorand();
    v6 = v3 ^ v9;
    fwrite(&v6, 1uLL, 1uLL, stream);
    ++v7;
  }
  fclose(stream);
  result = 0;
  v5 = *MK_FP(__FS__, 40LL) ^ v12;
  return result;
}
// 601064: using guessed type int seed;
// 40076B: using guessed type char ptr[88];

//----- (0000000000400890) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  signed __int64 v4; // rbp@1
  __int64 v5; // rbx@2

  v3 = a3;
  v4 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v5++])(a1, a2, v3);
    while ( v5 != v4 );
  }
}
// 600E10: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 600E18: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400904) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
