/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// size_t strlen(const char *s);
// int printf(const char *format, ...);
// char *fgets(char *s, int n, FILE *stream);
// int _gmon_start__(void); weak
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
FILE *_bss_start; // idb
char completed_7585; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004004D8) ----------------------------------------------------
int init_proc()
{
  void *v0; // rax@1

  v0 = &__gmon_start__;
  if ( &__gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 400560: using guessed type int _gmon_start__(void);

//----- (0000000000400570) ----------------------------------------------------
#error "400576: positive sp value has been found (funcsize=3)"

//----- (00000000004005A0) ----------------------------------------------------
int deregister_tm_clones()
{
  signed __int64 v0; // rax@1

  v0 = 6295639LL - (_QWORD)&_bss_start;
  if ( (unsigned __int64)(6295639LL - (_QWORD)&_bss_start) > 0xE )
    LODWORD(v0) = 0;
  return v0;
}

//----- (00000000004005E0) ----------------------------------------------------
int register_tm_clones()
{
  return 0;
}

//----- (0000000000400620) ----------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax@2

  if ( !completed_7585 )
  {
    result = deregister_tm_clones();
    completed_7585 = 1;
  }
  return result;
}
// 601058: using guessed type char completed_7585;

//----- (0000000000400640) ----------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 400640: could not find valid save-restore pair for rbp

//----- (0000000000400666) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int result; // eax@8
  __int64 v4; // rcx@8
  int v5; // [sp+18h] [bp-38h]@1
  int i; // [sp+1Ch] [bp-34h]@1
  char s[24]; // [sp+20h] [bp-30h]@1
  __int64 v8; // [sp+38h] [bp-18h]@1

  v8 = *MK_FP(__FS__, 40LL);
  printf("Please enter a key: ", argv, argv);
  fgets(s, 13, _bss_start);
  v5 = 0;
  for ( i = 0; i < strlen(s); ++i )
    v5 += s[i];
  if ( v5 != 1337 || strlen(s) != 12 )
    printf("Bad Key :( %s", s);
  else
    printf("Nice key :) %s", s);
  result = 0;
  v4 = *MK_FP(__FS__, 40LL) ^ v8;
  return result;
}
// 400666: using guessed type char s[24];

//----- (0000000000400750) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  signed __int64 v4; // rbp@1
  __int64 v5; // rbx@2

  v3 = a3;
  v4 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v5++])(a1, a2, v3);
    while ( v5 != v4 );
  }
}
// 600E10: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 600E18: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000004007C4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 9 function(s)"
